package plm.patientslikeme2.utils

object Constants {

    const val PASSWORD: String = "password"
    const val ANDROID: String = "android"
    const val CLIENT_UID: String = "k6di7S7RuPxR1Xgk8uZMpof7hoidvmk20jU9BURuhLA"

    const val BLUE: String = "BLUE"
    const val MAGENTA: String = "MAGENTA"
    const val TEAL: String = "TEAL"
    const val ORANGE: String = "ORANGE"
    const val SHARE_WITH_COMMUNITY: String = "Share with the community"
    const val PERSONAL: String = "Personal"
    const val PERSONAL_SMALL: String = "personal"
    const val TERMS_CONDITIONS: String = "https://www.patientslikeme.com/about/user_agreement"
    const val PRIVACY_URL: String = "https://www.patientslikeme.com/about/privacy_full"
    const val CRISIS_RESOURCES: String =
        "https://support.patientslikeme.com/hc/en-us/categories/200085220-Crisis-resources"
    const val HELP_CENTER: String = "https://support.patientslikeme.com/hc/en-us"
    const val MANAGE_ACCOUNT: String = "http://patientslikeme.com/account/manage"
    const val CONTACT_URL: String = "https://www.patientslikeme.com/about/contact"
    const val LOAD_MORE: String = "load_more"
    const val JOIN: String = "join"
    const val UNDO: String = "undo"
    const val EDIT: String = "edit"
    const val REPLY: String = "reply"
    const val ADD: String = "add"
    const val OPEN: String = "open"
    const val DELETE: String = "delete"
    const val REMOVE: String = "remove"
    const val FOLLOW: String = "follow"
    const val UN_FOLLOW: String = "un_follow"
    const val NEW_MESSAGE_FROM_PROFILE: String = "new_message_from_profile"
    const val NEW_MESSAGE_FROM_COMMUNITY: String = "new_message_from_community"
    const val NEW_MESSAGE_FROM_GROUP: String = "new_message_from_group"
    const val NEW_MESSAGE: String = "new_message"
    const val REPLY_MESSAGE: String = "reply_message"
    const val SEND: String = "Send"
    const val REPLY_CAP_FIRST_LETTER: String = "Reply"
    const val REPORT_AS_SPAM: String = "report_as_spam"
    const val OTHER_TREATMENTS: String = "Other Treatments"

    const val CHAR_140: Int = 140
    const val CHAR_80: Int = 90
    const val CHAR_85: Int = 85
    const val CHAR_60: Int = 65
    const val CHAR_40: Int = 40

    const val TYPE: String = "type"
    const val VALUE: String = "value"
    const val MODEL: String = "model"

    const val IS_LOGGED_IN: String = "is_logged_in"
    const val IS_REMEMBER_ME: String = "is_remember_me"
    const val USER_DEVICES: String = "user_devices"

    const val Preference = "patientslikeme2"
    const val ACCESS_TOKEN = "access_token"
    const val REFRESH_TOKEN = "refresh_token"
    const val TOKEN_TYPE = "token_type"
    const val EXPIRES_IN = "expires_in"
    const val SIGNUP_STEP = "signup_step"
    const val RESET_PASSWORD_TOKEN = "reset_password_token"
    const val USER = "user"
    const val AUTHORIZATION = "Authorization"
    const val APP_TYPE = "app-type"
    const val LOGIN_USER_NAME = "login_user_name"
    const val LOGIN_PASSWORD = "login_password"
    const val USER_NAME = "user_name"
    const val FONT_SIZE = "font_size"
    const val APP_THEME = "app_theme"
    const val PUBLIC_IV_PERSONAL = "PUBLIC_IV_PERSONAL"
    const val brightness: String = "brightness"
    const val MEMBER_FOLLOW: String = "Follow"
    const val MEMBER_UNFOLLOW: String = "Unfollow"
    const val MASTER_DATA: String = "master_data"
    const val MODERATE: String = "Moderate"
    const val NONE: String = "None"
    const val MILD: String = "Mild"
    const val SEVERE: String = "Severe"
    const val MAJOR: String = "Major"
    const val SEVERITY: String = "SEVERITY"
    const val PRIVACY: String = "PRIVACY"
    const val NOTIFICATION: String = "NOTIFICATION"
    const val AMPM: String = "AMPM"
    const val PURPOSE_TREATMENT_PURPOSE: String = "treatment_purpose"
    const val PURPOSE_CONDITION_INFO: String = "condition_info"
    const val PURPOSE_SYMPTOM_INFO: String = "symptom_info"
    const val PURPOSE_CONDITION: String = "condition"
    const val PURPOSE_SYMPTOM: String = "symptom"
    const val CONDITION_INFO: String = "condition_info"
    const val PLM: String = "plm"
    const val AM: String = "am"
    const val PM: String = "pm"
    val privacySettingList = arrayOf(
        "Share with the community", "Personal", "Please Select"
    )

    const val IMAGE_PICK_CODE = 1099

    const val GROUP_ID = "GROUP_ID"
    const val DISCUSSION_ID = "DISCUSSION_ID"
    const val COMMENT_ID = "COMMENT_ID"
    const val IS_MEMBER = "IS_MEMBER"
    const val GROUP_TITLE = "GROUP_TITLE"
    const val DISCUSSION_DETAILS = "DISCUSSION_DETAILS"
    const val GROUP_PRIVATE = "GROUP_PRIVATE"
    const val USER_ID = "USER_ID"
    const val METRIC_GUID = "metric_guid"
    const val CONDITION_ID = "CONDITION_ID"
    const val CONDITION_NAME = "CONDITION_NAME"
    const val ID = "id"
    const val NAME = "name"
    const val FOLLOWING_DISCUSSION = "following_discussion"
    const val FOLLOWING_RESOURCE = "following_resource"
    const val FOLLOWING_MEMBER = "following_member"
    const val FOLLOWING_TAG = "following_tag"
    const val COMMUNITY_EVENT = "community_event"
    const val GROUP_EVENT = "group_event"
    const val GROUP_RESOURCE = "group_resource"

    const val TREATMENT_REMINDERS = "treatment_reminders"
    const val GOAL_REMINDERS = "goal_reminders"
    const val PRIVATE_MESSAGES = "private_messages"
    const val REACTIONS_TO_DISCUSSION = "reactions_to_discussion"
    const val DISCUSSION_FOLLOWING = "discussion_following"
    const val SOMEONE_MENTIONED = "someone_mentioned"
    const val SOMEONE_FOLLOWING = "someone_following"
    const val DISCUSSION_STARTED = "discussion_started"
    const val NOTIFICATION_LIST: String = "notification_list"
    const val ENABLE = "enable"
    const val DISABLE = "disable"
    const val CONTEXT_ID = "context_id"
    const val CONTEXT_TYPE = "context_type"

    const val PERSONAL_INFORMATION = "personal_information"
    const val FOLLOWING = "following"
    const val COMMUNITY_MEMBER = "community_member"
    const val GROUP_MEMBER = "group_member"
    const val PRIVATE_MESSAGE = "private_message"
    const val PROFILE_PRIVATE_MESSAGE = "profile_private_message"
    const val SEND_A_WELCOME = "send_a_welcome"
    const val ABOUT_GROUP = "about_group"
    const val GROUP_DISCUSSIONS = "group_discussions"
    const val GROUP_DISCUSSIONS_DETAILS = "group_discussions_details"
    const val COMMUNITY_GROUP = "community_group"
    const val COMMUNITY_ALL_GROUP = "community_all_group"
    const val HOME_MY_GROUP = "home_my_group"
    const val HOME_PROMO_CARD_GROUP_OVERVIEW = "home_promo_card_group_overview"
    const val HOME_PROMO_CARD_GROUP_DISCUSSION = "home_promo_card_group_discussion"
    const val MY_FOLLOWINGS = "my_followings"
    const val DISCUSSION_REPLY = "discussion_reply"
    const val DISCUSSION_COMMENT = "discussion_comment"
    const val TAG_DETAILS = "tag_details"

    const val NEWEST = "newest"
    const val OPTIONS = "options"
    const val EMPTY = ""
    const val MOST_HELPFUL = "most_helpful"
    const val RECENT_ACTIVITY = "recent_activity"
    const val PROFILE_COLOR = "profile_color"
    const val PUSH_NOTIFICATION = "push_notification"

    const val MESSAGE_CONVERSATION_PAGE_COUNT = 10
    const val MESSAGES_PAGE_COUNT = 10
    const val OTHERS_MESSAGE = "others_message"
    const val WHOLE_THREAD = "whole_thread"
}
